version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail1:
    image: grafana/promtail:2.3.0
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /home/griffin/Shared/loki/production/promtail-config.yml:/tmp/config.yml
    # command: -config.file=/etc/promtail/config.yml
    command: -config.file=/tmp/config.yml
    networks:
      - loki
  
  promtail2:
    image: grafana/promtail:2.3.0
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /home/griffin/Shared/loki/production/promtail-config.yml:/tmp/config.yml
    # command: -config.file=/etc/promtail/config.yml
    command: -config.file=/tmp/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
